
export const Routers = {
  Dashboard: "/",
  Login: "/login",
  Register: "/register",
  VendorRegister: "/franchisee-register",
  VerifyBankDetails: "/verify-bank-details",
  ContentManagement: "/content-management",
  EarningManagement: "/earning-management",
  Invite: "/invite",
  EmailManagement: "/email-management",
  EmailMessage: "/email-message",
  InventoryManagement: "/inventory-management",
  ProductList: "/product-list",
  // CheckOut: "/checkout",
  ManageMembers: "/MR-manage-members",
  MembersProfile: "/MR-memberprofile/:id",
  AddProduct: "/add-product",
  AddCategories: "/add-category",
  AddCategoryType: "/add-category-type",
  AddCategoryBrand: "/add-category-brand",
  VendorManagement: "/vendor-management",
  Notification: "/notification",
  VendorDetails: "/vendor-details/:id",
  NotFound: "*",
  PRODUCT_MANAGEMENT: "/product-list",
  // CATEGORY_MANAGMENT:"/category-list",
  AddProductManagement: "/add-product-management",
  INVENTORY_MANAGEMENT: "/inventory-management",
  CONTENT_MANAGEMENT: "/content-management",
  EARNING_MANAGEMENT: "/earning-management",
  MANAGE_MEMBERS: "/MR-manage-members",
  EMAIL_MANAGEMENT: "/email-management",
  EMAIL_MESSAGE: "/email-message",
  VENDOR_MANAGEMENT: "/vendor-management",
  NOTIFICATION: "/notification",
  VENDOR_DETAILS: "/vendor-details",
  ADD_COUPON: "/offer-management",
  REWARD_MANAGEMENT: "/reward-management",
   MarketingTool:"/marketing-tool",
   MarketingToolAllVideos:"/all-get-videos",
   MarketingToolAllImages:"/all-get-images",
   MarketingToolAllPdf:"/all-get-pdf",
   STATIC_BANNER:"/static-banner",
  REFERRAL_MANAGEMENT: "/referral-management",
  GALLERY_MANAGEMENT: "/gallery-management",
  HISTORY:"/order-history",
  ProductDisplay:"/ProductDisplay",
  AllIncome:"/All-Income",
  UserList:"/UserList",
  ChangePasswordadmin:"/ChangePasswordadmin"
};
